// Lightweight server-side permission matrix for authorization.
// Kept separate so it can be imported by authorize middleware and future extensions.

export const rolePermissions = {
  Admin: {
    canViewDashboard: true,
    canViewTaxpayers: true,
    canAddTaxpayers: true,
    canEditTaxpayers: true,
    canDeleteTaxpayers: true,
    canViewDocuments: true,
    canAddDocuments: true,
    canEditDocuments: true,
    canDeleteDocuments: true,
    canApproveDocuments: true,
    canViewWorkflows: true,
    canCreateWorkflows: true,
    canEditWorkflows: true,
    canApproveWorkflows: true,
    canViewReports: true,
    canGenerateReports: true,
    canViewUsers: true,
    canAddUsers: true,
    canEditUsers: true,
    canDeleteUsers: true,
    canViewAuditLogs: true,
    canViewNotifications: true,
    canManageNotifications: true,
    canViewSettings: true,
    canEditSettings: true,
  },
  Officer: {
    canViewDashboard: true,
    canViewTaxpayers: true,
    canAddTaxpayers: true,
    canEditTaxpayers: true,
    canDeleteTaxpayers: false,
    canViewDocuments: true,
    canAddDocuments: true,
    canEditDocuments: true,
    canDeleteDocuments: false,
    canApproveDocuments: true,
    canViewWorkflows: true,
    canCreateWorkflows: true,
    canEditWorkflows: true,
    canApproveWorkflows: true,
    canViewReports: true,
    canGenerateReports: true,
    canViewUsers: false,
    canAddUsers: false,
    canEditUsers: false,
    canDeleteUsers: false,
    canViewAuditLogs: false,
    canViewNotifications: true,
    canManageNotifications: false,
    canViewSettings: false,
    canEditSettings: false,
  },
  Auditor: {
    // Audit mode: view-only for most resources, but allow dashboard + audit logs + workflows
    canViewDashboard: true,
    canViewTaxpayers: true,
    canAddTaxpayers: false,
    canEditTaxpayers: false,
    canDeleteTaxpayers: false,
    canViewDocuments: true,
    canAddDocuments: false,
    canEditDocuments: false,
    canDeleteDocuments: false,
    canApproveDocuments: false,
    canViewWorkflows: true,
    canCreateWorkflows: false,
    canEditWorkflows: false,
    canApproveWorkflows: false,
    canViewReports: true,
    canGenerateReports: false,
    canViewUsers: false,
    canAddUsers: false,
    canEditUsers: false,
    canDeleteUsers: false,
    canViewAuditLogs: true,
    canViewNotifications: true,
    canManageNotifications: false,
    canViewSettings: false,
    canEditSettings: false,
  },
  Supervisor: {
    // Supervisor mode: view workflows + pending items + approve workflows, but still keep user/audit log management restricted
    canViewDashboard: true,
    canViewTaxpayers: true,
    canAddTaxpayers: false,
    canEditTaxpayers: false,
    canDeleteTaxpayers: false,
    canViewDocuments: true,
    canAddDocuments: false,
    canEditDocuments: false,
    canDeleteDocuments: false,
    canApproveDocuments: true,
    canViewWorkflows: true,
    canCreateWorkflows: false,
    canEditWorkflows: false,
    canApproveWorkflows: true,
    canViewReports: true,
    canGenerateReports: false,
    canViewUsers: false,
    canAddUsers: false,
    canEditUsers: false,
    canDeleteUsers: false,
    // NOTE: supervisor dashboard does not fetch audit logs directly
    canViewAuditLogs: false,
    canViewNotifications: true,
    canManageNotifications: false,
    canViewSettings: false,
    canEditSettings: false,
  },
}

